version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: some-clickhouse-server
    restart: always
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./datagrip/dump.sql:/docker-entrypoint-initdb.d/dump.sql


